config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  mount Sidekiq::Web => "/sidekiq"

  root to: "cats#index"

  resources :cats, only: [:index] do
    post :serve, on: :collection
  end
end

app/models/cat_request.rb
class CatRequest < ActiveRecord::Base
  def fulfill!
    Cats.display! link
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cat_requests

  def cat_me!
    cat_request = cat_requests.create! link: Cats.sample
    cat_request.fulfill!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def serve
    @incoming = true
    CatServer.perform_later current_user
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title text
    content_for(:title) { text }
  end

  def flash_class name
    case name
    when :notice
      :success
    when :alert
      :error
    else
      name
    end
  end
end

app/views/cats/index.html.slim
= title "Cattr"

.inner
  .max-width
    .cta Push button. Receive Cat.
    - if @incoming
      | Kitten incoming. Would you like another?
    = button_to serve_cats_path, method: :post, id: "cat_button", class: "button" do
      i.fa.fa-paw
      | Cat Me

javascript:
  $(".inner form").submit(function() {
    $("#cat_button").
      addClass("disabled").
      attr("disabled", true).
      html("<i class='fa fa-spinner fa-spin'></i>Herding Cats…");
  });

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? "#{yield :title} | DCRUG" : "DCRUG"

    = csrf_meta_tags

    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"
    /= javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

    /= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Open+Sans:300,400"
    = stylesheet_link_tag "application", media: "all"
  body
    .container
      .flash
        - flash.each do |name, msg|
          div class="alert alert-#{flash_class name}"
            a.close data-dismiss="alert"
              | &times;
            div id="flash_#{flash_class name}"
              = msg

      = yield